### ISSUE TITLE
Monitoring RF signals from Keychain Remote

### ISSUE THREAD

**Issue by roberthuttinger** [bschollnick/Indigo-Switchboard#5]
Hey friend, I am using a KR32A style remote with 6 buttons (arm, disarm, lights on, off, and two panic). The RF receiver is getting the signals and showing the correct button pushed. I had to completely nuke my set up due to dead HDD and failed backup... so... is it possible to read log events and trigger appropriately? I thought this was possible with switchboard. Currently using Indigo 6. I tried the built in commands but when set to change a variable the action doesnt bubble out.

**Comment by bschollnick** [comment]
Bo,

Switchboard monitors existing devices, and automatically runs triggers based on the activity…

While the quick summary specifically calls out X10 devices, even Insteon devices will work with Switchboard. 

http://www.schollnick.net/wordpress/home-automation/indigo-v5-plugins/switchboard/ <http://www.schollnick.net/wordpress/home-automation/indigo-v5-plugins/switchboard/>

Do you have any monitored device groups defined?

	- Benjamin

**Comment by roberthuttinger** [comment]
I have Switchboard set to monitor insteon and X10.

I tried setting up monitored groups, however I need to be able to define the device so I can add it to the group.

When I reload Switchboard (SB) I get the error: `An unregistered X10 device has been detected. Security ID is 190`

When I try to set the remote up as a device, I give it the address of 190. Then reload SB.  I get the error: `Name_Of_Device [1197060526] not been assigned a monitored Device Group`. 

In the log, when I push the disarm button I get an object:
`address : `
`avFunc : None`
`cmdSuccess : true`
`cmdType : sec`
`secCodeId : 190`
`secFunc : disarm`
`x10DimBrightLevel : None`
`x10ExtendedData : None`
`x10Func : None`
`x10PresetVal : None`

So it looks like the RF is getting the individual commands eg: `security command arm away (min delay) (ID 190)`

So I tried setting up triggers > condition: `if device` `{my_device_name}` `The last x10 command received contains` `disarm`

as well as same in the trigger itself. Perhaps the question is how can I set the keychain up as a device properly in the first place. I was hoping I'd be able to capture events. 

Im willing to get in and hack some code if the plugin can get me partially there. I tried adjusting the string parsing in the plugin.py file to accept the specific strings in case the event log is being read.

Thoughts friend?

Appreciate the plugin! It certainly fills a void, Im just hoping I can utilize it!

[https://forums.indigodomo.com/viewtopic.php?f=87&t=25731](url)

**Comment by bschollnick** [comment]
Bo,

Have you created a “X10 Monitored Device” record for Security ID 190?
Can you please attach a screen shot of the device?

Once the X10 Monitor device has been created switchboard will then be able to use it.

Looking at your message, I suspect the X10 Monitored Device has been created.

Then create a monitored device group, add the X10 Monitored Device to it, and then turn on “Action Group Support” for that group.

Turn on Action Group Support, takes the type of action (e.g. Open, Closed, TurnOn, TurnOff, etc) and will run an action group that you designated in the text field and append the action to the Action Group name.  For example, if the Action Group name is “Kitchen”, when a door sensor is opened, it would attempt to run the “Kitchen_Open” Action Group.
Then you would create a trigger <Monitored Device Group Name>_Disarm, which would disarm your security (the trigger would set the variable, or whatever you need to do).

And you’d also want to create <Monitored Device Group Name>_Arm, <Monitored Device Group Name>_Panic, etc.

The current list of actions that are recognized, and the Action Group names, are:
On           (XYZ_On)
Off           (XYZ_Off)
Open       (XYZ_Open)
Closed     (XYZ_Closed)
Armed     (XYZ_Armed)
Disarm    (XYZ_Disarm)
Panic       (XYZ_Panic)
LightsOn    (XYZ_LightsOn)
LightsOff      (XYZ_LightsOff)
	- Benjamin

**Comment by roberthuttinger** [comment]
BINGO! it has a learning curve and in this case knowing the UI of Indigo helped as your descriptions were on point. Perhaps I can add more human readable instructions and merge request. Hey, thanks a ton, I believe this will get me there with a little work!

**Comment by roberthuttinger** [comment]
I wrote up a walkthrough for others, will link here for posterity, thanks again! [https://forums.indigodomo.com/viewtopic.php?f=87&t=25731&p=206992#p206992](url)
